added environment config to each script

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,8 +1,9 @@
 #!/bin/bash
+# Install ni into a common location
 # Author: Nick Zwart
 # Date: 2019dec31
-# Brief: build the docker image for ni.
 
+set -euo pipefail
 
 ####################################################################### INCLUDE
 # assume config is in the same dir
@@ -10,4 +11,13 @@ source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/config.bash ; config
 
 
 ########################################################################## MAIN
-docker build -t ${DOCKER_ACC}/${DOCKER_REP}:${DOCKER_TAG} .
+# check for existing hook
+if [ -f "${CMD_DEST}" ]; then
+    echo "A script named ${CMD_SRC} is already installed:"
+    echo "    ${CMD_DEST}"
+    echo "Install aborted."
+    exit 1
+fi
+
+# link the script
+cp -v $CMD_SRC $CMD_DEST
